import { Inter } from "next/font/google";
import "./globals.css";
import axios from "axios";
import OrderContext from "../context/OrderContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // let themeStyle = {};

  // try {
  //   const res = await axios.get(
  //     "https://groww-intern-assignment.vercel.app/v1/api/merchant-metadata"
  //   );

  //   if (res?.data?.theme) {
  //     themeStyle = {
  //       "--background": `${res?.data?.theme?.["--background"]}`,
  //       "--foreground": `${res?.data?.theme?.["--foreground"]}`,
  //       "--primary": `${res?.data?.theme?.["--primary"]}`,
  //       "--primary-foreground": `${res?.data?.theme?.["--primary-foreground"]}`,
  //     };
  //   }
  // } catch (e) {}

  return (
    <html lang="en">
      <body className={inter.className}>
        <OrderContext>{children}</OrderContext>
      </body>
    </html>
  );
}
